dockerui:
  image: dockerui/dockerui:latest
  expose:
    - 9000
  ports:
    - 9000:9000
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

apache:
  build: apache
  ports:
    - 80:80
  links:
    - jboss:jboss
  volumes:
    - /container_data/apache/logs:/usr/local/apache2/logs

webapp:
  build: webapp
  ports:
    - 8090:8080
  links:
    - mysql
    - activemq
    - elasticsearch
    - elasticsearchbis:elasticsearch2
  volumes:
    - /container_data/webapp/logs:/opt/webapp/logs

jboss:
  build: jboss
  expose:
    - 8009
# You can make JBoss visible from the Docker host if exposing the port 8080.
#  ports:
#    - 8080:8080
  links:
    - mysql
    - activemq
  volumes:
    - /container_data/jboss/log:/opt/jboss/server/default/log

mysql:
  build: mysql
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: taskmanager
    MYSQL_USER: user
    MYSQL_PASSWORD: user
  volumes:
    - /container_data/mysql:/var/lib/mysql

activemq:
  image: webcenter/activemq:latest
  ports:
    - 8161:8161
    - 61616:61616
    - 61613:61613
  environment:
    ACTIVEMQ_NAME: amq
    ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: 'True'
    ACTIVEMQ_ADMIN_LOGIN: admin
    ACTIVEMQ_ADMIN_PASSWORD: admin
  volumes:
    - /container_data/activemq/data:/data/activemq
    - /container_data/activemq/log:/var/log/activemq

elasticsearch:
  build: elasticsearch
  ports:
    - 9200:9200
    - 9300:9300
  environment:
    ES_JAVA_OPTS: -Des.node.name=elasticsearch -Des.network.host=${DOCKER_HOST_IP} -Des.transport.tcp.port=9300 -Des.http.port=9200 -Des.discovery.zen.ping.multicast.enabled=false -Des.discovery.zen.ping.unicast.hosts=${DOCKER_HOST_IP}:9301
  volumes:
    - /container_data/elasticsearch/data:/usr/share/elasticsearch/data

elasticsearchbis:
  build: elasticsearch
  ports:
    - 9201:9201
    - 9301:9301
  environment:
    ES_JAVA_OPTS: -Des.node.name=elasticsearch_bis -Des.network.host=${DOCKER_HOST_IP} -Des.transport.tcp.port=9301 -Des.http.port=9201 -Des.discovery.zen.ping.multicast.enabled=false -Des.discovery.zen.ping.unicast.hosts=${DOCKER_HOST_IP}:9300
  volumes:
    - /container_data/elasticsearchbis/data:/usr/share/elasticsearch/data
